/*
  # Enhanced Crawling and Flow Tracking

  1. New Tables
    - `page_interactive_elements` - Store interactive elements identified on each page
      - Links to discovered_pages
      - Stores element type, selector, text, attributes
      - Vision LLM identification metadata

    - `crawl_paths` - Track crawling paths taken
      - Sequence of pages visited
      - Interaction performed to reach next page
      - Enables browser restart from specific points
      - Prevents duplicate path exploration

    - `user_flows` - Store meaningful user flows identified by LLM
      - Multi-page sequences representing user journeys
      - Links to test cases that cover the flow
      - Flow-level test generation

    - `page_metadata` - Extended page information
      - Screen name (auto-generated by LLM)
      - Page type classification
      - Crawl session information

  2. Schema Enhancements
    - Add screen_name to discovered_pages
    - Add flow_id to test_cases for flow-level tests
    - Add playwright_code to test_cases for executable tests

  3. Security
    - Enable RLS on all new tables
    - Add policies for authenticated users
*/

-- Page Interactive Elements table
CREATE TABLE IF NOT EXISTS page_interactive_elements (
    id SERIAL PRIMARY KEY,
    page_id INTEGER REFERENCES discovered_pages(id) ON DELETE CASCADE,
    element_type VARCHAR(100) NOT NULL,
    selector TEXT NOT NULL,
    text_content TEXT,
    attributes JSONB DEFAULT '{}',
    position JSONB DEFAULT '{}',
    is_visible BOOLEAN DEFAULT true,
    interaction_priority VARCHAR(50) DEFAULT 'medium' CHECK (interaction_priority IN ('high', 'medium', 'low')),
    identified_by VARCHAR(50) DEFAULT 'vision_llm' CHECK (identified_by IN ('vision_llm', 'dom_parser', 'hybrid')),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Crawl Paths table
CREATE TABLE IF NOT EXISTS crawl_paths (
    id SERIAL PRIMARY KEY,
    test_run_id INTEGER REFERENCES test_runs(id) ON DELETE CASCADE,
    from_page_id INTEGER REFERENCES discovered_pages(id),
    to_page_id INTEGER REFERENCES discovered_pages(id),
    interaction_element_id INTEGER REFERENCES page_interactive_elements(id),
    interaction_type VARCHAR(50) NOT NULL,
    interaction_details JSONB DEFAULT '{}',
    path_sequence INTEGER NOT NULL,
    depth_level INTEGER NOT NULL,
    is_dead_end BOOLEAN DEFAULT false,
    can_navigate_back BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(test_run_id, from_page_id, to_page_id, interaction_element_id)
);

-- User Flows table
CREATE TABLE IF NOT EXISTS user_flows (
    id SERIAL PRIMARY KEY,
    test_run_id INTEGER REFERENCES test_runs(id) ON DELETE CASCADE,
    flow_name VARCHAR(500) NOT NULL,
    flow_description TEXT,
    flow_type VARCHAR(100),
    page_sequence JSONB NOT NULL,
    interaction_sequence JSONB NOT NULL,
    business_value TEXT,
    estimated_coverage_impact DECIMAL(5,2),
    identified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add screen_name and page_type to discovered_pages
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'discovered_pages' AND column_name = 'screen_name'
  ) THEN
    ALTER TABLE discovered_pages ADD COLUMN screen_name VARCHAR(500);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'discovered_pages' AND column_name = 'page_type'
  ) THEN
    ALTER TABLE discovered_pages ADD COLUMN page_type VARCHAR(100);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'discovered_pages' AND column_name = 'page_source'
  ) THEN
    ALTER TABLE discovered_pages ADD COLUMN page_source TEXT;
  END IF;
END $$;

-- Add flow_id and playwright_code to test_cases
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'test_cases' AND column_name = 'flow_id'
  ) THEN
    ALTER TABLE test_cases ADD COLUMN flow_id INTEGER REFERENCES user_flows(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'test_cases' AND column_name = 'playwright_code'
  ) THEN
    ALTER TABLE test_cases ADD COLUMN playwright_code TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'test_cases' AND column_name = 'test_level'
  ) THEN
    ALTER TABLE test_cases ADD COLUMN test_level VARCHAR(50) DEFAULT 'page' CHECK (test_level IN ('page', 'flow'));
  END IF;
END $$;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_page_interactive_elements_page_id ON page_interactive_elements(page_id);
CREATE INDEX IF NOT EXISTS idx_page_interactive_elements_element_type ON page_interactive_elements(element_type);
CREATE INDEX IF NOT EXISTS idx_crawl_paths_test_run_id ON crawl_paths(test_run_id);
CREATE INDEX IF NOT EXISTS idx_crawl_paths_from_page_id ON crawl_paths(from_page_id);
CREATE INDEX IF NOT EXISTS idx_crawl_paths_to_page_id ON crawl_paths(to_page_id);
CREATE INDEX IF NOT EXISTS idx_crawl_paths_depth_level ON crawl_paths(depth_level);
CREATE INDEX IF NOT EXISTS idx_user_flows_test_run_id ON user_flows(test_run_id);
CREATE INDEX IF NOT EXISTS idx_test_cases_flow_id ON test_cases(flow_id);

-- Enable Row Level Security
ALTER TABLE page_interactive_elements ENABLE ROW LEVEL SECURITY;
ALTER TABLE crawl_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_flows ENABLE ROW LEVEL SECURITY;

-- RLS Policies for page_interactive_elements
CREATE POLICY "Users can view interactive elements from their test runs"
  ON page_interactive_elements FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM discovered_pages dp
      JOIN test_runs tr ON tr.id = dp.test_run_id
      JOIN test_configs tc ON tc.id = tr.test_config_id
      WHERE dp.id = page_interactive_elements.page_id
      AND tc.created_by = auth.uid()
    )
  );

CREATE POLICY "System can insert interactive elements"
  ON page_interactive_elements FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- RLS Policies for crawl_paths
CREATE POLICY "Users can view crawl paths from their test runs"
  ON crawl_paths FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM test_runs tr
      JOIN test_configs tc ON tc.id = tr.test_config_id
      WHERE tr.id = crawl_paths.test_run_id
      AND tc.created_by = auth.uid()
    )
  );

CREATE POLICY "System can insert crawl paths"
  ON crawl_paths FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update crawl paths"
  ON crawl_paths FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- RLS Policies for user_flows
CREATE POLICY "Users can view flows from their test runs"
  ON user_flows FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM test_runs tr
      JOIN test_configs tc ON tc.id = tr.test_config_id
      WHERE tr.id = user_flows.test_run_id
      AND tc.created_by = auth.uid()
    )
  );

CREATE POLICY "System can insert user flows"
  ON user_flows FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE page_interactive_elements IS 'Interactive elements identified by vision LLM on each page';
COMMENT ON TABLE crawl_paths IS 'Tracks the sequence of pages and interactions during crawling';
COMMENT ON TABLE user_flows IS 'Meaningful user journeys identified across multiple pages';
